# https://docs.travis-ci.com/user/languages/java/#projects-using-gradle
language: java
# https://www.deps.co/guides/travis-ci-latest-java/
jdk:
  - oraclejdk11
  - openjdk11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    # https://scan.coverity.com/projects/queryhub-queryhub/builds/new?tab=travis_ci
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "Qq2UEWWnSSwSdzy3BQ/OGxLH7BOPZmqk9mNtQ5Ttt0zSa32cRnI0xCXZ5+JwEdiLfHI0lY4/AdEpZZTG99zKXN1fR+fKfbxBcn/zX/tNqCW3s+PkHGUT5NAAoi8MOROUdNHVNTloM0fwscRD8VSYtNO/CpGCJMDzyvrOzMt84pBSx5aEH+n8cz8hQA7LgVgbn30uwjhEvjppIQSLJRO0ScfeDKb6hjzVVModwH3YFKCskFbCCUCfg4l1qI0hS0n+A45GjjqSweccXKfIbbdIDZBKVM9Mtz300MzyWFa9lGqNKrgx8oD09i46Xd1TfCK7RWJsga+L4bZjBQUGKoginVMf+Ff06i+xOghojiAAVK0LAg8dC8p8IBSUgco1+vVIFpEr+IFGJYdczc3c4uL+smrJHOLOaJNnAEghvnheHOeDQROhkdpsw4QKqYA4SukIwbK3P0LAQCQaJcGKdmIqOnIu3KFAVnhGfc11TKe9aRd/zBoKqVdWAId+7rZqpeM6EZ/qSig6HDIgOIaiELE2FqB5PyXhDk9cX6bykfEORTiTaO/QY7m2GBSHI8A3EynWXsc0RZ1cp74+qL4qNaa68trEf7IPVuUblvWdorG1jivQ+fSsm0thgv/flzPEjiHaGnT/zgtZPVMmp2ZvV0hs4IXPT69s0u762EKaw+QbASU="

addons:
  # https://docs.travis-ci.com/user/sonarcloud/
  sonarcloud:
    organization: queryhub
    token:
      secure: "fe78c047c663a9859f71f618f499434eeb4d901a"
  # https://scan.coverity.com/projects/queryhub-queryhub/builds/new?tab=travis_ci
  coverity_scan:
    project:
      name: queryhub/queryhub
      description: Small Java DSL for easing SQL query building.
    notification_email: queryhub.pub@gmail.com
    # build_command_prepend: "<Your build preprocessing command here>"
    # build_command: "<Your build command here>"
    branch_pattern: coverity_scan

before_install:
  # https://scan.coverity.com/projects/queryhub-queryhub/builds/new?tab=travis_ci
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

# https://github.com/codecov/example-gradle#-do-you-support-multi-module-projects
after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - ./gradlew check sonarqube
