# https://docs.travis-ci.com/user/languages/java/#projects-using-gradle
language: java
# https://www.deps.co/guides/travis-ci-latest-java/
jdk:
  - oraclejdk11
  - openjdk11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# https://docs.travis-ci.com/user/sonarcloud/
addons:
  sonarcloud:
    organization: "queryhub"
    token:
      secure: "fe78c047c663a9859f71f618f499434eeb4d901a"

script:
  ./gradlew -i clean check jacocoTestCoverageVerification jacocoTestReport sonarqube